### ISSUE TITLE
Нет переноса строки в /team у судьи

### ISSUE THREAD

**Issue by artem-kucher** [AdvanceRoleplay/mod-bugs#1]
!ВОЗМОЖНО УЖЕ ПОФИКШЕНО, Я ХЗ)!
В автоотчёте у судьи некорректно отображается информация. Нет переноса строки
![dk9wng2rnjq](https://user-images.githubusercontent.com/24384253/36639992-360a9150-1a20-11e8-8144-cafe2c6bf2c5.jpg)

**Comment by advance-roleplay** [comment]
Исправлено
